### ISSUE TITLE
Change Todos.js to functional based component

### ISSUE THREAD

**Issue by sumanssaurabh** [sumanssaurabh/reactjs-todo-app#1]

**Comment by jennybean** [comment]
@sumanssaurabh I'm happy to help with this once #Hacktoberfest starts tomorrow!

**Comment by RohithChittibommala** [comment]
@sumanssaurabh  can I work on this issue

**Comment by sumanssaurabh** [comment]
@jennybean sure i have already assigned you for the same

**Comment by supanthapaul** [comment]
I have created a PR for the same.
